services:
  - type: web
    name: landing
    env: python
    plan: free
    buildCommand: "pip install -r requirements.txt"
    startCommand: "gunicorn prueba1.wsgi:application"
    envVars:
      - key: PYTHON_VERSION
        value: 3.12
