# Generated by Django 6.0.4 on 2026-05-13 01:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Registro",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=150)),
                ("correo", models.EmailField(max_length=254, unique=True)),
                ("codigo", models.CharField(max_length=6)),
                ("verificado", models.BooleanField(default=False)),
                ("creado", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
